Product:
  type: object
  properties:
    product_id:
      type: integer
      example: 1
    name:
      type: string
      example: 'Aceite Diésel 15W40'
    description:
      type: string
      example: 'Aceite mineral para motores diésel de alto rendimiento'
    price:
      type: number
      format: float
      example: 45000.00
    size:
      type: string
      enum: ['small', 'medium', 'large']
      example: 'medium'
    stock_quantity:
      type: integer
      example: 100
    image_url:
      type: string
      format: uri
      example: 'https://example.com/images/aceite-15w40.jpg'
    reference:
      type: string
      example: 'REF-001'
    visible:
      type: boolean
      example: true
    active:
      type: boolean
      example: true
    created_at:
      type: string
      format: date-time
      example: '2023-10-01T12:00:00Z'
    categories:
      type: array
      items:
        $ref: './category.yaml#/Category'
  required:
    - product_id
    - name
    - price
    - size
    - stock_quantity
    - created_at
    - categories
    - visible
    - active

ProductCreate:
  type: object
  properties:
    category_ids:
      type: array
      items:
        type: integer
      example: [1, 2]
      description: Optional array of category IDs
    name:
      type: string
      example: 'Aceite Diésel 15W40'
    description:
      type: string
      example: 'Aceite mineral para motores diésel de alto rendimiento'
    price:
      type: number
      format: float
      example: 45000.00
    size:
      type: string
      enum: ['small', 'medium', 'large']
      example: 'medium'
    stock_quantity:
      type: integer
      example: 100
    image_url:
      type: string
      format: uri
      example: 'https://example.com/images/aceite-15w40.jpg'
    reference:
      type: string
      example: 'REF-001'
  required:
    - name
    - price
    - size
    - stock_quantity

ProductUpdate:
  type: object
  properties:
    category_ids:
      type: array
      items:
        type: integer
      example: [1, 3]
    name:
      type: string
      example: 'Aceite Diésel 15W40 Premium'
    description:
      type: string
      example: 'Descripción actualizada'
    price:
      type: number
      format: float
      example: 50000.00
    size:
      type: string
      enum: ['small', 'medium', 'large']
      example: 'large'
    stock_quantity:
      type: integer
      example: 150
    image_url:
      type: string
      format: uri
      example: 'https://example.com/images/aceite-premium.jpg'
    reference:
      type: string
      example: 'REF-001-UPDATED'
    visible:
      type: boolean
      example: false
  # No required fields for update

ProductsList:
  type: array
  items:
    $ref: '#/Product'
